### ISSUE TITLE
PopOverComp.js

### ISSUE THREAD

**Issue by ShawnKoga** [maintmind/record-management-app#23]
We are getting some errors due to missing keys in the .map iterations.
Also the popover menu and badges don't work 100% correct.
I cleaned up some of the errors we were getting from the component, but didn't finish them all.

**Comment by james-carlson** [comment]
We have keys in the component for the dynamic parts of the array. Still getting the error. Will keep looking into it.

**Comment by james-carlson** [comment]
The issue on the component was that our key was not located on the outer-most div. Should be fixed as soon as it's pulled into Master.
