### ISSUE TITLE
PhotoUploader in LogModal

### ISSUE THREAD

**Issue by marissafisch** [maintmind/record-management-app#37]
Now that I have added some padding into the Modal, we need to fix the PhotoUploader "drag an drop" verbiage in the Modal once the photo is uploaded

**Comment by james-carlson** [comment]
Good catch. I will take a look at this.

**Comment by james-carlson** [comment]
The photo upload dropzone will disappear now when you upload...we'll have to fix this if we implement the ability to upload multiple images.

But for now the image will fit within the modal.
