### ISSUE TITLE
Need user_id in more tables/endpoints

### ISSUE THREAD

**Issue by james-carlson** [maintmind/record-management-app#5]
I think we need to add foreign keys referencing user IDs in all tables and at least these additional endpoints:

**server.js**
```
//ASSETS ENDPOINTS
app.get('/api/assets/get_all/:id', controller.getAllAssets)
app.post('/api/assets/add', controller.addAsset)

//CATEGORY ENDPOINTS
app.get('/api/categories/get_all/:id', controller.getAllCategories)
app.post('/api/categories/add', controller.addCategory)
```

Also we might want to change the endpoints to show which id we are using, rather than just id.

**Comment by ShawnKoga** [comment]
Updated the endpoints and sql files to work the correct way
