### ISSUE TITLE
Need to add actions to reducer

### ISSUE THREAD

**Issue by james-carlson** [maintmind/record-management-app#9]
We need some additional actions in the reducer to control the display of the user input form. 

Suggestions:

actions:
TOGGLE_USER_INPUT_FORM_NEW_ASSET
TOGGLE_USER_INPUT_FORM_NEW_CATEGORY
TOGGLE_USER_INPUT_FORM_NEW_LOG

Initial state: 
displayFormNewAsset: false
displayFormNewCategory: false
displayFormNewLog: false

**Comment by marissafisch** [comment]
In state 
modalToggler
can be equal to
false, 'asset', 'cat','log', 'reminder'

**Comment by james-carlson** [comment]
Sounds great. Not sure if we can mix false (boolean) with strings? I think we can do null though and then use strings later...

**Comment by james-carlson** [comment]
For future record: went with null. Everything is updated.
